Repository DavidAndreRoca/ClinicaVillegas_Backend, pull requests merged in 2025-06, with the labels that each got.

#17 test(controllers): Implementar pruebas unitarias para los controladores.
  pom.xml
  src/main/java/com/clinicavillegas/app/chat/controllers/ComentarioController.java
  src/main/java/com/clinicavillegas/app/chat/dto/request/ComentarioRequest.java
  src/main/java/com/clinicavillegas/app/chat/dto/response/ComentarioResponse.java
  src/main/java/com/clinicavillegas/app/chat/mappers/ComentarioMapper.java
  src/main/java/com/clinicavillegas/app/chat/services/ComentarioService.java
  src/main/java/com/clinicavillegas/app/chat/services/DefaultComentarioService.java
  src/test/java/com/clinicavillegas/app/JpaTestConfig.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/CitaControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/DentistaControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/HorarioControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/TratamientoControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/repositories/TipoTratamientoRepositoryTest.java
  src/test/java/com/clinicavillegas/app/auth/controllers/AuthControllerTest.java
  src/test/java/com/clinicavillegas/app/chat/controllers/ComentarioControllerTest.java
  src/test/java/com/clinicavillegas/app/email/controllers/EmailControllerTest.java
  src/test/java/com/clinicavillegas/app/user/controllers/ApiReniecControllerTest.java
  src/test/java/com/clinicavillegas/app/user/controllers/TipoDocumentoControllerTest.java
  src/test/java/com/clinicavillegas/app/user/controllers/UsuarioControllerTest.java
Labels: test

#19 test(repositories): Implementar pruebas unitarias exhaustivas para los repositorios.
  src/test/java/com/clinicavillegas/app/appointment/repositories/CitaRepositoryTest.java
  src/test/java/com/clinicavillegas/app/appointment/repositories/DentistaRepositoryTest.java
  src/test/java/com/clinicavillegas/app/appointment/repositories/HorarioRepositoryTest.java
  src/test/java/com/clinicavillegas/app/appointment/repositories/TratamientoRepositoryTest.java
  src/test/java/com/clinicavillegas/app/chat/repositories/ComentarioRepositoryTest.java
  src/test/java/com/clinicavillegas/app/user/repositories/TipoDocumentoRepositoryTest.java
  src/test/java/com/clinicavillegas/app/user/repositories/UsuarioRepositoryTest.java
Labels: test

#20 feat(caché): implementar caché en la aplicación
  pom.xml
  src/main/java/com/clinicavillegas/app/appointment/services/impl/DefaultCitaService.java
  src/main/java/com/clinicavillegas/app/appointment/services/impl/DefaultDentistaService.java
  src/main/java/com/clinicavillegas/app/auth/config/SecurityConfig.java
  src/main/java/com/clinicavillegas/app/chat/services/impl/DefaultComentarioService.java
  src/main/java/com/clinicavillegas/app/common/cache/config/CacheConfig.java
  src/main/java/com/clinicavillegas/app/user/services/TipoDocumentoService.java
  src/main/java/com/clinicavillegas/app/user/services/impl/DefaultTipoDocumentoService.java
  src/main/java/com/clinicavillegas/app/user/services/impl/DefaultUsuarioService.java
  src/main/resources/application.yml
  src/test/java/com/clinicavillegas/app/user/services/TipoDocumentoServiceTest.java
Labels: enhancement

#22 Feature/auth refactor
  src/main/java/com/clinicavillegas/app/auth/config/JwtAuthenticationFilter.java
  src/main/java/com/clinicavillegas/app/auth/config/SecurityConfig.java
  src/main/java/com/clinicavillegas/app/auth/controllers/AuthController.java
  src/main/java/com/clinicavillegas/app/auth/dto/response/AuthResponse.java
  src/main/java/com/clinicavillegas/app/auth/dto/response/JwtResponse.java
  src/main/java/com/clinicavillegas/app/auth/exceptions/InvalidTokenException.java
  src/main/java/com/clinicavillegas/app/auth/exceptions/TokenExpiredException.java
  src/main/java/com/clinicavillegas/app/auth/models/Session.java
  src/main/java/com/clinicavillegas/app/auth/models/TokenType.java
  src/main/java/com/clinicavillegas/app/auth/repositories/SessionRepository.java
  src/main/java/com/clinicavillegas/app/auth/services/AuthService.java
  src/main/java/com/clinicavillegas/app/auth/services/CookieService.java
  src/main/java/com/clinicavillegas/app/auth/services/JwtService.java
  src/main/java/com/clinicavillegas/app/auth/services/impl/DefaultAuthService.java
  src/main/java/com/clinicavillegas/app/common/GlobalExceptionHandler.java
  src/main/java/com/clinicavillegas/app/email/services/impl/DefaultEmailService.java
  src/main/java/com/clinicavillegas/app/user/services/ApiReniecService.java
  src/main/java/com/clinicavillegas/app/user/services/UsuarioService.java
  src/main/resources/application.yml
  src/test/java/com/clinicavillegas/app/appointment/controllers/CitaControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/DentistaControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/HorarioControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/TipoTratamientoControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/TratamientoControllerTest.java
  src/test/java/com/clinicavillegas/app/auth/controllers/AuthControllerTest.java
  src/test/java/com/clinicavillegas/app/auth/services/AuthServiceTest.java
  src/test/java/com/clinicavillegas/app/chat/controllers/ComentarioControllerTest.java
  src/test/java/com/clinicavillegas/app/email/controllers/EmailControllerTest.java
  src/test/java/com/clinicavillegas/app/user/controllers/ApiReniecControllerTest.java
  src/test/java/com/clinicavillegas/app/user/controllers/TipoDocumentoControllerTest.java
  src/test/java/com/clinicavillegas/app/user/controllers/UsuarioControllerTest.java
Labels: enhancement

#24 feat(paginación): implementación de paginación para múltiples entidades.
  src/main/java/com/clinicavillegas/app/AppApplication.java
  src/main/java/com/clinicavillegas/app/appointment/controllers/CitaController.java
  src/main/java/com/clinicavillegas/app/appointment/controllers/DentistaController.java
  src/main/java/com/clinicavillegas/app/appointment/controllers/TipoTratamientoController.java
  src/main/java/com/clinicavillegas/app/appointment/controllers/TratamientoController.java
  src/main/java/com/clinicavillegas/app/appointment/services/CitaService.java
  src/main/java/com/clinicavillegas/app/appointment/services/DentistaService.java
  src/main/java/com/clinicavillegas/app/appointment/services/TipoTratamientoService.java
  src/main/java/com/clinicavillegas/app/appointment/services/TratamientoService.java
  src/main/java/com/clinicavillegas/app/appointment/services/impl/DefaultCitaService.java
  src/main/java/com/clinicavillegas/app/appointment/services/impl/DefaultDentistaService.java
  src/main/java/com/clinicavillegas/app/appointment/services/impl/DefaultTipoTratamientoService.java
  src/main/java/com/clinicavillegas/app/appointment/services/impl/DefaultTratamientoService.java
  src/main/java/com/clinicavillegas/app/appointment/specifications/DentistaSpecification.java
  src/main/java/com/clinicavillegas/app/appointment/specifications/TipoTratamientoSpecification.java
  src/main/java/com/clinicavillegas/app/audit/JpaConfig.java
  src/main/java/com/clinicavillegas/app/auth/config/SecurityConfig.java
  src/main/java/com/clinicavillegas/app/chat/controllers/ComentarioController.java
  src/main/java/com/clinicavillegas/app/chat/mappers/ComentarioMapper.java
  src/main/java/com/clinicavillegas/app/chat/repositories/ComentarioRepository.java
  src/main/java/com/clinicavillegas/app/chat/services/ComentarioService.java
  src/main/java/com/clinicavillegas/app/chat/services/impl/DefaultComentarioService.java
  src/main/java/com/clinicavillegas/app/user/controllers/TipoDocumentoController.java
  src/main/java/com/clinicavillegas/app/user/controllers/UsuarioController.java
  src/main/java/com/clinicavillegas/app/user/services/TipoDocumentoService.java
  src/main/java/com/clinicavillegas/app/user/services/UsuarioService.java
  src/main/java/com/clinicavillegas/app/user/services/impl/DefaultTipoDocumentoService.java
  src/main/java/com/clinicavillegas/app/user/services/impl/DefaultUsuarioService.java
  src/main/resources/application.yml
  src/test/java/com/clinicavillegas/app/appointment/controllers/CitaControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/DentistaControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/TipoTratamientoControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/controllers/TratamientoControllerTest.java
  src/test/java/com/clinicavillegas/app/appointment/services/DentistaServiceTest.java
  src/test/java/com/clinicavillegas/app/appointment/services/TipoTratamientoServiceTest.java
  src/test/java/com/clinicavillegas/app/appointment/services/TratamientoServiceTest.java
  src/test/java/com/clinicavillegas/app/chat/controllers/ComentarioControllerTest.java
  src/test/java/com/clinicavillegas/app/chat/services/ComentarioServiceTest.java
  src/test/java/com/clinicavillegas/app/user/controllers/TipoDocumentoControllerTest.java
  src/test/java/com/clinicavillegas/app/user/controllers/UsuarioControllerTest.java
  src/test/java/com/clinicavillegas/app/user/services/TipoDocumentoServiceTest.java
  src/test/java/com/clinicavillegas/app/user/services/UsuarioServiceTest.java
Labels: enhancement

#27 Feature/dynamic reports
  src/main/java/com/clinicavillegas/app/appointment/models/Cita.java
  src/main/java/com/clinicavillegas/app/auth/config/SecurityConfig.java
  src/main/java/com/clinicavillegas/app/reports/controllers/ReporteController.java
  src/main/java/com/clinicavillegas/app/reports/dto/ReporteRequestDTO.java
  src/main/java/com/clinicavillegas/app/reports/services/ReportePdfService.java
  src/main/java/com/clinicavillegas/app/reports/services/ReporteService.java
  src/main/java/com/clinicavillegas/app/user/models/Usuario.java
  src/main/resources/static/logo.jpg
  src/test/java/com/clinicavillegas/app/appointment/repositories/CitaRepositoryTest.java
  src/test/java/com/clinicavillegas/app/appointment/repositories/DentistaRepositoryTest.java
  src/test/java/com/clinicavillegas/app/appointment/repositories/HorarioRepositoryTest.java
  src/test/java/com/clinicavillegas/app/chat/repositories/ComentarioRepositoryTest.java
Labels: enhancement

#28 Feature/dynamic reports
  pom.xml
  src/main/java/com/clinicavillegas/app/appointment/controllers/CitaController.java
  src/main/java/com/clinicavillegas/app/appointment/services/impl/DefaultCitaService.java
  src/main/java/com/clinicavillegas/app/chat/controllers/ComentarioController.java
  src/main/java/com/clinicavillegas/app/common/CorsConfig.java
  src/main/java/com/clinicavillegas/app/reports/controllers/ReporteController.java
  src/main/java/com/clinicavillegas/app/reports/services/ReporteExcelService.java
  src/main/java/com/clinicavillegas/app/reports/services/ReportePdfService.java
  src/main/resources/application.yml
  src/test/java/com/clinicavillegas/app/appointment/services/CitaServiceTest.java
  src/test/java/com/clinicavillegas/app/chat/controllers/ComentarioControllerTest.java
Labels: enhancement

#31 feat(correo): Agregar correos de notificación
  Dockerfile
  src/main/java/com/clinicavillegas/app/appointment/services/impl/DefaultCitaService.java
  src/main/java/com/clinicavillegas/app/email/MailTemplates.java
  src/main/java/com/clinicavillegas/app/email/services/EmailService.java
  src/main/java/com/clinicavillegas/app/email/services/impl/DefaultEmailService.java
  src/test/java/com/clinicavillegas/app/appointment/services/CitaServiceTest.java
Labels: help wanted

#32 chore: Cambio del atributo SameSite en la cookie
  src/main/java/com/clinicavillegas/app/auth/services/CookieService.java
Labels: help wanted
